### ISSUE TITLE
Decrypt/Encrypt message

### ISSUE THREAD

**Issue by ReshetovItsMe** [ReshetovItsMe/one-time-messaging-exchange-be#7]
The best effect is achieved with a combination of symmetric and asymmetric types of encryption. The way this works is as follows:
- A session key for symmetric encryption is sent to the server through the asymmetric algorithm;
- Information is exchanged using the symmetric algorithm.

There are variations, but the general sense usually does not change.

The most popular symmetric algorithm - **AES** (crypto/aes and crypto/cipher modules in Golang)
The most popular asymmetric algorithm - **RSA** (crypto/rsa and crypto/rand modules in Golang)

Also we can research new **ChaCha** asymmetric algorithm

**Comment by Kriognot** [comment]
насрал в коммент
